[tool.poetry]
name = "calc-profit"
version = "0.1.0"
description = ""
authors = ["scott.xing <scott.xing@solactive.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
